coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "crates/fhir/src/r4.rs"
  - "crates/fhir/src/r4b.rs"
  - "crates/fhir/src/r5.rs"
  - "crates/fhir/src/r6.rs"